Fixed docker builds for sdidt in python

diff --git a/docker/python/Dockerfile b/docker/python/Dockerfile
--- a/docker/python/Dockerfile
+++ b/docker/python/Dockerfile
@@ -10,8 +10,6 @@ FROM python:3.7
 
 RUN apt-get update
 RUN apt-get -y install apt-transport-https libtbb-dev rapidjson-dev sudo
-RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
-RUN apt-get -y install npm
 RUN apt-get -y remove python3
 
 RUN wget https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.sh -q
@@ -24,21 +22,25 @@ RUN rm -fr /opt/cmake/bin/cpack
 RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
 RUN ln -s /opt/cmake/bin/ctest /usr/local/bin/ctest
 
-RUN python3.7 -m pip install numpy pandas
+RUN python3.7 -m pip install numpy pandas cython codecov nose2 mock flake8 pytest pytest-cov traitlets ipywidgets faker psutil zerorpc
 
-RUN ls -al /usr/local/lib/python3.7/site-packages/numpy
-
-RUN wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz >/dev/null 2>&1  || echo "wget failed"
+# install boost
+RUN wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz >/dev/null 2>&1  || echo "wget boost failed"
 RUN tar xfz boost_1_71_0.tar.gz
 # https://github.com/boostorg/build/issues/468
-RUN cd boost_1_71_0 && CPLUS_INCLUDE_PATH="/usr/local/include/python3.7m" C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/python3.7m" ./bootstrap.sh --with-python=/usr/local/bin/python3.7 || echo "boostrap failed"
-RUN cd boost_1_71_0 && CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/local/include/python3.7m" C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/python3.7m" ./b2 -j4 install || echo "build boost failed" 
+RUN cd boost_1_71_0 && ./bootstrap.sh || echo "boostrap failed"
+RUN cd boost_1_71_0 && ./b2 -j4 install || echo "build boost failed" 
 
-RUN ln -s /usr/local/lib/libboost_python37.so /usr/local/lib/libboost_python.so
-RUN ln -s /usr/local/lib/libboost_numpy37.so /usr/local/lib/libboost_numpy.so
+RUN python3 -m pip install 'numpy>=1.13.1' 'pandas>=0.22.0'
 
-RUN python3 -m pip install codecov nose2 mock flake8 pytest pytest-cov traitlets ipywidgets faker psutil zerorpc
-RUN python3 -m pip install 'numpy>=1.13.1' 'pandas>=0.22.0' 'pyarrow==0.15.0'
+# install pyarrow
+RUN wget https://github.com/apache/arrow/archive/apache-arrow-0.15.0.tar.gz >/dev/null 2>&1  || echo "wget arrow failed"
+RUN tar xfz apache-arrow-0.15.0.tar.gz
+RUN cd arrow-apache-arrow-0.15.0 && mkdir build && cd build && cmake ../cpp/ -DARROW_RPATH_ORIGIN=ON -DARROW_PYTHON=ON -DARROW_FLIGHT=ON -DARROW_COMPUTE=ON -DCMAKE_INSTALL_PREFIX=/usr -DARROW_DATASET=OFF -DARROW_BUILD_UTILITIES=OFF -DARROW_JEMALLOC=OFF -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_HDFS=OFF -DARROW_WITH_BACKTRACE=OFF -DARROW_WITH_BROTLI=OFF -DARROW_WITH_BZ2=OFF -DARROW_WITH_LZ4=OFF -DARROW_WITH_SNAPPY=OFF -DARROW_WITH_ZLIB=OFF -DARROW_WITH_ZSTD=OFF && make -j2 && sudo make install && cd ../python && sudo python3.7 setup.py install
+
+# install node
+RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
+RUN apt-get -y install nodejs
 
 RUN npm install --global yarn
 RUN yarn --version
